"""empty message

Revision ID: 03fcbda67f77
Revises: abc2b6318f29
Create Date: 2023-11-24 11:06:41.345817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fcbda67f77'
down_revision = 'abc2b6318f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_data', schema=None) as batch_op:
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###
