"""empty message

Revision ID: 076ae07de9f0
Revises: f59f83fcba43
Create Date: 2023-11-21 17:46:54.469365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '076ae07de9f0'
down_revision = 'f59f83fcba43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plat_id', sa.Integer(), nullable=True))
        batch_op.alter_column('attention',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'plat', ['plat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('attention',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.drop_column('plat_id')

    # ### end Alembic commands ###
