"""empty message

Revision ID: 1bdbde8de2b2
Revises: aefa3ee9439d
Create Date: 2023-11-24 10:38:22.543613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bdbde8de2b2'
down_revision = 'aefa3ee9439d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('follow', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upgradetime', sa.DateTime(), nullable=True))
        batch_op.drop_column('ave_collected')
        batch_op.drop_column('liked_rate')
        batch_op.drop_column('collected_rate')
        batch_op.drop_column('ave_liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ave_liked', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('collected_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('liked_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ave_collected', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('upgradetime')
        batch_op.drop_column('createtime')

    op.drop_table('account_data')
    # ### end Alembic commands ###
