"""empty message

Revision ID: 32290a4e509a
Revises: a738dd1f3560
Create Date: 2023-11-18 18:08:09.432456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32290a4e509a'
down_revision = 'a738dd1f3560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prtype', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    with op.batch_alter_table('prtype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
