"""empty message

Revision ID: 3aa19123d742
Revises: 39d4400d2f7c
Create Date: 2023-11-27 11:24:17.308567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa19123d742'
down_revision = '39d4400d2f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['pvcontent.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bloger', ['bloger_id'], ['id'])
        batch_op.create_foreign_key(None, 'plat', ['plat_id'], ['id'])

    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('liked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commented', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('forwarded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('imageList', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contenttype', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('spyder_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attention', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upload_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upgrade_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goods_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['content_id'])
        batch_op.create_foreign_key(None, 'group', ['goods_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('goods_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('create_time')
        batch_op.drop_column('upgrade_time')
        batch_op.drop_column('upload_time')
        batch_op.drop_column('attention')
        batch_op.drop_column('status')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('contenttype')
        batch_op.drop_column('imageList')
        batch_op.drop_column('video_link')
        batch_op.drop_column('content_link')
        batch_op.drop_column('forwarded')
        batch_op.drop_column('commented')
        batch_op.drop_column('collected')
        batch_op.drop_column('liked')
        batch_op.drop_column('desc')
        batch_op.drop_column('content_id')
        batch_op.drop_column('title')
        batch_op.drop_column('search_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('content_keyword')
    op.drop_table('keyword')
    # ### end Alembic commands ###
