"""empty message

Revision ID: 44bd94467039
Revises: 378954d8e264
Create Date: 2023-11-27 11:08:54.105072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44bd94467039'
down_revision = '378954d8e264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint('pvcontent_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('pvcontent_ibfk_2', type_='foreignkey')
        batch_op.drop_column('account_id')
        batch_op.drop_column('goods_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pvcontent_ibfk_2', 'group', ['goods_id'], ['id'])
        batch_op.create_foreign_key('pvcontent_ibfk_1', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###
