"""empty message

Revision ID: 4ce8033229d6
Revises: 3cd601a9c97d
Create Date: 2023-11-27 12:47:55.829220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce8033229d6'
down_revision = '3cd601a9c97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('account_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('account_ibfk_2', type_='foreignkey')
        batch_op.drop_column('gender')
        batch_op.drop_column('self')
        batch_op.drop_column('nickname')
        batch_op.drop_column('createtime')
        batch_op.drop_column('location')
        batch_op.drop_column('upgradetime')
        batch_op.drop_column('attention')
        batch_op.drop_column('plat_id')
        batch_op.drop_column('fans')
        batch_op.drop_column('boards')
        batch_op.drop_column('profile_link')
        batch_op.drop_column('desc')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('search_id')
        batch_op.drop_column('officialVerifyName')
        batch_op.drop_column('account_id')
        batch_op.drop_column('liked')
        batch_op.drop_column('collected')
        batch_op.drop_column('follow')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('bloger_id')

    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint('pvcontent_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pvcontent_ibfk_1', type_='foreignkey')
        batch_op.drop_column('video_link')
        batch_op.drop_column('goods_id')
        batch_op.drop_column('content_link')
        batch_op.drop_column('commented')
        batch_op.drop_column('attention')
        batch_op.drop_column('desc')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('search_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('upgrade_time')
        batch_op.drop_column('title')
        batch_op.drop_column('liked')
        batch_op.drop_column('create_time')
        batch_op.drop_column('forwarded')
        batch_op.drop_column('collected')
        batch_op.drop_column('imageList')
        batch_op.drop_column('contenttype')
        batch_op.drop_column('upload_time')
        batch_op.drop_column('content_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('content_id', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('upload_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('contenttype', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('imageList', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('collected', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('forwarded', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('liked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('upgrade_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('search_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('spyder_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('desc', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('attention', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commented', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_link', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_link', mysql.VARCHAR(length=200), nullable=True))
        batch_op.create_foreign_key('pvcontent_ibfk_1', 'group', ['goods_id'], ['id'])
        batch_op.create_foreign_key('pvcontent_ibfk_2', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloger_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('notes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('follow', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('collected', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('liked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_id', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('officialVerifyName', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('search_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('spyder_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('desc', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_link', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('boards', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fans', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plat_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attention', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upgradetime', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('createtime', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nickname', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('self', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('account_ibfk_2', 'plat', ['plat_id'], ['id'])
        batch_op.create_foreign_key('account_ibfk_1', 'bloger', ['bloger_id'], ['id'])

    # ### end Alembic commands ###
