"""empty message

Revision ID: 57b51716488e
Revises: fdb3e3898fcf
Create Date: 2023-11-18 15:01:46.168945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b51716488e'
down_revision = 'fdb3e3898fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PVtype', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_column('PVtype')

    # ### end Alembic commands ###
