"""empty message

Revision ID: 688a4f7bcb8b
Revises: 21cbdc6db8b2
Create Date: 2023-11-26 18:44:47.175176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '688a4f7bcb8b'
down_revision = '21cbdc6db8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyToken', schema=None) as batch_op:
        batch_op.alter_column('webid',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyToken', schema=None) as batch_op:
        batch_op.alter_column('webid',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
