"""empty message

Revision ID: 6a9cf9ac7095
Revises: 44bd94467039
Create Date: 2023-11-27 11:09:49.874798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9cf9ac7095'
down_revision = '44bd94467039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_column('content_id')
        batch_op.drop_column('upgrade_time')
        batch_op.drop_column('upload_time')
        batch_op.drop_column('search_id')
        batch_op.drop_column('imageList')
        batch_op.drop_column('liked')
        batch_op.drop_column('attention')
        batch_op.drop_column('desc')
        batch_op.drop_column('forwarded')
        batch_op.drop_column('create_time')
        batch_op.drop_column('title')
        batch_op.drop_column('collected')
        batch_op.drop_column('status')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('commented')
        batch_op.drop_column('content_link')
        batch_op.drop_column('contenttype')
        batch_op.drop_column('video_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_link', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('contenttype', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('content_link', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('commented', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('spyder_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('collected', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('forwarded', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desc', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('attention', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('liked', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imageList', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('search_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('upload_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('upgrade_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content_id', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
