"""add kdzs token

Revision ID: 8f8635b24b44
Revises: b9540173730a
Create Date: 2023-10-26 17:09:54.447140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8635b24b44'
down_revision = 'b9540173730a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kdzs_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kdzs_token', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
