"""empty message

Revision ID: 9a9a6a75a706
Revises: ca51a39f2dff
Create Date: 2023-11-27 14:18:52.848145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9a6a75a706'
down_revision = 'ca51a39f2dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plat', ['plat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plat_id')

    # ### end Alembic commands ###
