"""empty message

Revision ID: abc2b6318f29
Revises: 1bdbde8de2b2
Create Date: 2023-11-24 10:53:41.852469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc2b6318f29'
down_revision = '1bdbde8de2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attention', sa.Integer(), nullable=True))

    with op.batch_alter_table('account_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upgradetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_data', schema=None) as batch_op:
        batch_op.drop_column('upgradetime')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('attention')

    # ### end Alembic commands ###
