"""empty message

Revision ID: b62aa409a623
Revises: 57b51716488e
Create Date: 2023-11-18 15:44:50.803789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b62aa409a623'
down_revision = '57b51716488e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_column('PVtype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PVtype', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
