"""add kdzs token

Revision ID: b9540173730a
Revises: 52754fc2d5b5
Create Date: 2023-10-26 17:00:23.921473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9540173730a'
down_revision = '52754fc2d5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kdzs_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kdzs_token')
    # ### end Alembic commands ###
