"""empty message

Revision ID: ca51a39f2dff
Revises: 4ce8033229d6
Create Date: 2023-11-27 12:49:48.606150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca51a39f2dff'
down_revision = '4ce8033229d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('follow', sa.Integer(), nullable=True),
    sa.Column('upgradetime', sa.DateTime(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=False),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('commented', sa.Integer(), nullable=True),
    sa.Column('forwarded', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('pvcontent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pvcontent_id'], ['pvcontent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('boards', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('officialVerifyName', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fans', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attention', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('self', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('spyder_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upgradetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bloger_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bloger', ['bloger_id'], ['id'])
        batch_op.create_foreign_key(None, 'plat', ['plat_id'], ['id'])

    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('liked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commented', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('forwarded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('imageList', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contenttype', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('spyder_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attention', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upload_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upgrade_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goods_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'group', ['goods_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goods_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('create_time')
        batch_op.drop_column('upgrade_time')
        batch_op.drop_column('upload_time')
        batch_op.drop_column('attention')
        batch_op.drop_column('status')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('contenttype')
        batch_op.drop_column('imageList')
        batch_op.drop_column('video_link')
        batch_op.drop_column('content_link')
        batch_op.drop_column('forwarded')
        batch_op.drop_column('commented')
        batch_op.drop_column('collected')
        batch_op.drop_column('liked')
        batch_op.drop_column('desc')
        batch_op.drop_column('content_id')
        batch_op.drop_column('title')
        batch_op.drop_column('search_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plat_id')
        batch_op.drop_column('bloger_id')
        batch_op.drop_column('upgradetime')
        batch_op.drop_column('createtime')
        batch_op.drop_column('spyder_url')
        batch_op.drop_column('status')
        batch_op.drop_column('self')
        batch_op.drop_column('attention')
        batch_op.drop_column('gender')
        batch_op.drop_column('follow')
        batch_op.drop_column('collected')
        batch_op.drop_column('liked')
        batch_op.drop_column('fans')
        batch_op.drop_column('desc')
        batch_op.drop_column('officialVerifyName')
        batch_op.drop_column('location')
        batch_op.drop_column('boards')
        batch_op.drop_column('profile_link')
        batch_op.drop_column('notes')
        batch_op.drop_column('nickname')
        batch_op.drop_column('account_id')
        batch_op.drop_column('search_id')

    op.drop_table('pvdata')
    op.drop_table('account_data')
    # ### end Alembic commands ###
