"""empty message

Revision ID: cb58df7342d9
Revises: 
Create Date: 2023-05-31 18:54:55.461806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb58df7342d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atom_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('wechat', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dyToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feemodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('output_mode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('EH_name', sa.String(length=20), nullable=True),
    sa.Column('is_Store', sa.Boolean(), nullable=True),
    sa.Column('is_Promotion', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xhsToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wechat', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('wechat')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('follow', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Integer(), nullable=True),
    sa.Column('boards', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('ave_collected', sa.Float(), nullable=True),
    sa.Column('collected_rate', sa.Float(), nullable=True),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('ave_liked', sa.Float(), nullable=True),
    sa.Column('liked_rate', sa.Float(), nullable=True),
    sa.Column('officialVerifyName', sa.String(length=30), nullable=True),
    sa.Column('spyder_url', sa.String(length=200), nullable=True),
    sa.Column('profile_link', sa.String(length=200), nullable=True),
    sa.Column('bloger_id', sa.Integer(), nullable=True),
    sa.Column('plat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloger_id'], ['bloger.id'], ),
    sa.ForeignKeyConstraint(['plat_id'], ['plat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admethod',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=True),
    sa.Column('plat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plat_id'], ['plat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('atom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['atom_category.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['permission_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('sale_name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wechat', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=10), nullable=True),
    sa.Column('card', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('degree', sa.String(length=20), nullable=True),
    sa.Column('university', sa.String(length=20), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('jointime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('atoms_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atomid', sa.Integer(), nullable=True),
    sa.Column('saleid', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atomid'], ['atom.id'], ),
    sa.ForeignKeyConstraint(['saleid'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('county',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('distribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('campany_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wechat', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('province', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('freight', sa.Integer(), nullable=False),
    sa.Column('other', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=30), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission_table',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('sales_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plat_store_name', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('bindTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('plat_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['plat_id'], ['plat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=50), nullable=True),
    sa.Column('campany_name', sa.String(length=50), nullable=False),
    sa.Column('campany_simple_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('wechat', sa.String(length=20), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adfee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('admethod_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admethod_id'], ['admethod.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atoms_supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atomid', sa.Integer(), nullable=True),
    sa.Column('supplierid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atomid'], ['atom.id'], ),
    sa.ForeignKeyConstraint(['supplierid'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_stract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_parent_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('express', sa.String(length=30), nullable=True),
    sa.Column('expressOrder', sa.String(length=30), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('distribution_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['hand_category.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('orderID', sa.String(length=50), nullable=False),
    sa.Column('province', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('totalPayment', sa.Float(), nullable=True),
    sa.Column('totalReceivedPayment', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('express', sa.String(length=30), nullable=True),
    sa.Column('expressOrder', sa.String(length=30), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('payTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orderID')
    )
    op.create_table('purchase-atom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('atom_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atom_id'], ['atom.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('refund', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('payment_img', sa.String(length=50), nullable=True),
    sa.Column('express', sa.String(length=30), nullable=True),
    sa.Column('expressOrder', sa.String(length=30), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('hand_parent_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hand_parent_order_id'], ['hand_parent_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('orderID', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('refund', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('payment_img', sa.String(length=50), nullable=True),
    sa.Column('express', sa.String(length=30), nullable=True),
    sa.Column('expressOrder', sa.String(length=30), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_order_id'], ['parent_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orderID')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('feeImgLink', sa.String(length=100), nullable=True),
    sa.Column('orderstatus', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('bloger_id', sa.Integer(), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.Column('feeModel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloger_id'], ['bloger.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['feeModel_id'], ['feemodel.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['parent_order.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('refund_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('modifiedTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_order_id'], ['parent_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liveing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('liveing_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('living_date', sa.DateTime(), nullable=False),
    sa.Column('timelength', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('cooperation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cooperation_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_acount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('acount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acount_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_plats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('plat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plat_id'], ['plat.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvcontent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('commented', sa.Integer(), nullable=True),
    sa.Column('forwarded', sa.Integer(), nullable=True),
    sa.Column('content_link', sa.String(length=200), nullable=True),
    sa.Column('video_link', sa.String(length=200), nullable=True),
    sa.Column('spyder_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('output_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['output_mode.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('pvcontent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pvcontent_id'], ['pvcontent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.String(length=100), nullable=False),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('collected', sa.Integer(), nullable=True),
    sa.Column('commented', sa.Integer(), nullable=True),
    sa.Column('forwarded', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('pvcontent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pvcontent_id'], ['pvcontent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvdata')
    op.drop_table('comment')
    op.drop_table('pvcontent')
    op.drop_table('promotion_plats')
    op.drop_table('promotion_groups')
    op.drop_table('promotion_acount')
    op.drop_table('liveing')
    op.drop_table('refund')
    op.drop_table('promotion')
    op.drop_table('order')
    op.drop_table('hand_order')
    op.drop_table('sale_store')
    op.drop_table('purchase-atom')
    op.drop_table('parent_order')
    op.drop_table('hand_parent_order')
    op.drop_table('code_stract')
    op.drop_table('atoms_supplier')
    op.drop_table('adfee')
    op.drop_table('supplier')
    op.drop_table('store')
    op.drop_table('sales_groups')
    op.drop_table('role_permission_table')
    op.drop_table('purchase')
    op.drop_table('distribution')
    op.drop_table('county')
    op.drop_table('atoms_sales')
    op.drop_table('user')
    op.drop_table('sale')
    op.drop_table('province')
    op.drop_table('permission')
    op.drop_table('atom')
    op.drop_table('admethod')
    op.drop_table('account')
    op.drop_table('xhsToken')
    op.drop_table('unit')
    op.drop_table('role')
    op.drop_table('rate')
    op.drop_table('plat')
    op.drop_table('permission_category')
    op.drop_table('output_mode')
    op.drop_table('hand_category')
    op.drop_table('group')
    op.drop_table('feemodel')
    op.drop_table('dyToken')
    op.drop_table('city')
    op.drop_table('brand')
    op.drop_table('bloger')
    op.drop_table('atom_category')
    # ### end Alembic commands ###
