"""empty message

Revision ID: da4ce02dee32
Revises: de378cc9aa86
Create Date: 2023-11-22 15:10:39.961589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da4ce02dee32'
down_revision = 'de378cc9aa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
