"""empty message

Revision ID: df9668c9f8eb
Revises: d8a64191b155
Create Date: 2023-11-20 10:56:47.666612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df9668c9f8eb'
down_revision = 'd8a64191b155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wechat',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('_password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('wechat',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
