"""empty message

Revision ID: e919b968c601
Revises: c61ba7bda132
Create Date: 2023-05-31 19:44:50.599543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e919b968c601'
down_revision = 'c61ba7bda132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('hand_order', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
