"""empty message

Revision ID: fdb3e3898fcf
Revises: 28c5550517c4
Create Date: 2023-11-18 14:39:00.189130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb3e3898fcf'
down_revision = '28c5550517c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('self', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenttype', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prtype_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prtype', ['prtype_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvcontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prtype_id')
        batch_op.drop_column('contenttype')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('self')

    op.drop_table('prtype')
    # ### end Alembic commands ###
